### PR TITLE
- fixed lowest_rate() selector to handle comma separated string values

### PR DESCRIPTION
**Pull request by catokx**

### CODE REVIEW

**Comment by fthobe** [comment]
Hi @mwaldt , my colleague @catokx made a grade contribution to your library. Could you take a look as the python library is currently (since roughly 12 hours) broken as DHL changed the format for price quotes.

**Comment by mwaldt** [comment]
Hi,

I pushed an internal fix to the carrier on our end this morning. In the
future I would recommend reaching out to support@easypost.com with
inquiries such as these for more expedited results. I cc'd our support line
here as well for your convenience.

Cheers,

**Comment by fthobe** [comment]
@mwaldt it didn’t work for us. The fix @catokx pushed fixes variations in the format of the price, wouldn’t it make sense to merge it or does it break anything (values >999.99)?

**Comment by fthobe** [comment]
@mwaldt we did speak to customer support, they advised us to open an issue in GitHub!

**Comment by Justintime50** [comment]
@fthobe @catokx has this been an issue since? I believe this has been patched since initially being submitted and wanted to know if indeed it had or not.

**Pull request closed without merging**
