### PR TITLE
add conditional check if the http is 204 to prevent error being thrown.

### PR DESCRIPTION
**Pull request by jchen293**
When deleting a child user, our API endpoint will return HTTP 204 with an empty response body. This is a special case because HTTP 204 means the request is succeeded but doesn't have a response body, in our Python library it will throw an error because we never handle this corner, the root of the cause is `json.loads` in the `interpret_response` method because an error will be thrown when the response body is empty even thought the HTTP request is succeeded. See the screenshot below.

This PR checks if the HTTP Status response is 204, since the response body is empty the `json.loads()` will throw an error. Adding an if statement to handle the corner case.

Error stack: 
Screen Shot 2022-04-04 at 1 51 13 PM

### CODE REVIEW

**Comment by Justintime50** [comment]
Can you please elaborate on why this is needed and provide the error stack that occurs when this fix is not in place?

**Comment by jchen293** [comment]
> Can you please elaborate on why this is needed and provide the error stack that occurs when this fix is not in place?

I have elaborate the PR description.

**Comment by Justintime50** [comment]
We should re-record the cassette that will use this updated logic as part of this PR to ensure it works.

**Comment by jchen293** [comment]
> We should re-record the cassette that will use this updated logic as part of this PR to ensure it works.

`Webhook` and `carrier_account` are the only two that use this updated delete logic. For deleting a child user, I have E2E locally tested.

**Review by Justintime50 — APPROVED** [review]

**Comment by Justintime50** [comment]
I'm curious why this didn't break before?

**Comment by jchen293** [comment]
> I'm curious why this didn't break before?

`test_user_delete` is skipped in our unit test and this is by far the only API endpoint that returns HTTP 204 with an empty body.

**Comment by nwithan8** [comment]
As opposed to specifically checking for a 204 status code, why don't we handle an empty JSON body inside `interpret_response`?

**Comment by jchen293** [comment]
> As opposed to specifically checking for a 204 status code, why don't we handle an empty JSON body inside `interpret_response`?

HTTP 204 guarantees the return JSON body is empty, I am unsure if there will be a case from the API endpoint returning an empty JSON body for HTTP code that is other than 204.

**Review by Justintime50 — APPROVED** [review]

**Review by nwithan8 — APPROVED** [review]

**Pull request merged**
