### PR TITLE
Adding unit tests

### PR DESCRIPTION
**Pull request by wyounas**
Hello,

I hope this finds you well. Just did two things:

1- Added unit tests in the code. Mostly used API docs and example_*.py files as a reference. One test (tests/pickup.py) isn't working as yet, I might need some help with that.
2- Put all example code under examples/

Kindly let me know if there are any more changes I can make or if there is anything I can correct. Thanks in advance.

### CODE REVIEW

**Comment by wyounas** [comment]
Hello ( @sawyer and @victoryftw ),

I was just wondering if the changes look good and can be merged? If there is anything more I need to do please let me know. Thanks.

**Comment by att14** [comment]
Hey @wyounas, sorry no one has gotten around to this. I think most of the changes look great and we really appreciate the pull request. We had a busy couple weeks and added a bunch of functionality to this repo. I will look at this as soon as I can next week.

**Comment by wyounas** [comment]
Hello @att14 ,

Sure, no problem. Please let me know if there is anything I can do to get the code merged in. If there are any changes I can make, please feel free to let me know.

Thank you.

**Comment by victoryftw** [comment]
Hey @wyounas, sorry again for the delay on this. I finally got some time to work today on bringing this up-to-date with the current version of the repo (making the new examples into tests) and fixing the Pickup tests; got mostly done so hopefully we'll get it merged tomorrow! Thanks again for doing this!

**Comment by victoryftw** [comment]
Thanks for all the help @wyounas! We made a few stylistic changes and fixed the pickup tests, and everything is merged now!

**Pull request merged**
